import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}


export const appointmentsData = [
  {
    id: 1,
    title: "Appointment for 4A Math Test",
    class: "4A",
    date: "2025-01-01",
    time: "10:00 AM",
    doctor: "Dr. Smith",
    patient: "Alice Johnson",
    gender: "Female", // Added gender field
    actions: ["view", "reject", "cancel"],
  },
  {
    id: 2,
    title: "Appointment for 3A Math Test",
    class: "3A",
    date: "2025-01-01",
    time: "11:00 AM",
    doctor: "Dr. Johnson",
    patient: "Bob Williams",
    gender: "Male",
    actions: ["view", "reject", "cancel"],
  },
  {
    id: 3,
    title: "Appointment for 3B Math Test",
    class: "3B",
    date: "2025-01-01",
    time: "12:00 PM",
    doctor: "Dr. Carter",
    patient: "Charlie Brown",
    gender: "Male",
    actions: ["view", "reject", "cancel"],
  },
  {
    id: 4,
    title: "Appointment for 6A Math Test",
    class: "6A",
    date: "2025-01-01",
    time: "1:00 PM",
    doctor: "Dr. Brown",
    patient: "Diana Adams",
    gender: "Female",
    actions: ["view", "reject", "cancel"],
  },
  {
    id: 5,
    title: "Appointment for 8C Math Test",
    class: "8C",
    date: "2025-01-01",
    time: "2:00 PM",
    doctor: "Dr. Taylor",
    patient: "Ella Martin",
    gender: "Female",
    actions: ["view", "reject", "cancel"],
  },
  {
    id: 6,
    title: "Appointment for 2A Math Test",
    class: "2A",
    date: "2025-01-01",
    time: "9:00 AM",
    doctor: "Dr. Anderson",
    patient: "Frank Miller",
    gender: "Male",
    actions: ["view", "reject", "cancel"],
  },
  {
    id: 7,
    title: "Appointment for 4C Math Test",
    class: "4C",
    date: "2025-01-01",
    time: "3:00 PM",
    doctor: "Dr. Garcia",
    patient: "Grace Hall",
    gender: "Female",
    actions: ["view", "reject", "cancel"],
  },
  {
    id: 8,
    title: "Appointment for 4B Math Test",
    class: "4B",
    date: "2025-01-01",
    time: "4:00 PM",
    doctor: "Dr. Martinez",
    patient: "Hannah King",
    gender: "Female",
    actions: ["view", "reject", "cancel"],
  },
  {
    id: 9,
    title: "Appointment for 3C Math Test",
    class: "3C",
    date: "2025-01-01",
    time: "5:00 PM",
    doctor: "Dr. Lee",
    patient: "Ian Garcia",
    gender: "Male",
    actions: ["view", "reject", "cancel"],
  },
  {
    id: 10,
    title: "Appointment for 1C Math Test",
    class: "1C",
    date: "2025-01-01",
    time: "6:00 PM",
    doctor: "Dr. Perez",
    patient: "Jack Wilson",
    gender: "Male",
    actions: ["view", "reject", "cancel"],
  },
  {
    id: 11,
    title: "Appointment for 1C Math Test",
    class: "1C",
    date: "2025-01-01",
    time: "6:00 PM",
    doctor: "Dr. Perez",
    patient: "Roshan",
    gender: "Male",
    actions: ["view", "reject", "cancel"],
  },
];
